"""Tests verifying that agent comment footers include the model identifier."""
import pytest


def test_requirements_agent_footer_includes_model():
    """RequirementsAgent._format_comment includes model line in footer."""
    from app.agents.requirements_agent import RequirementsAgent

    # Create minimal agent without real API keys (model defaults from settings)
    agent = RequirementsAgent.__new__(RequirementsAgent)
    agent.model = "anthropic/claude-3.5-sonnet"

    data = {
        "enriched_title": "As a user, I want to login with OAuth",
        "acceptance_criteria": ["Given X, When Y, Then Z"],
        "edge_cases": ["Invalid token"],
        "suggested_labels": ["auth"],
        "complexity": "M",
    }

    comment = agent._format_comment(data, agent.model)

    assert "*Model: anthropic/claude-3.5-sonnet*" in comment
    assert "*Generated by RepoGator Requirements Agent using RAG knowledge base*" in comment


def test_requirements_agent_footer_uses_custom_model():
    """Footer reflects the actual model, not a hardcoded value."""
    from app.agents.requirements_agent import RequirementsAgent

    agent = RequirementsAgent.__new__(RequirementsAgent)
    agent.model = "openai/gpt-4o"

    data = {
        "enriched_title": "Title",
        "acceptance_criteria": ["AC"],
        "edge_cases": ["Edge"],
        "suggested_labels": ["label"],
        "complexity": "S",
    }

    comment = agent._format_comment(data, agent.model)
    assert "*Model: openai/gpt-4o*" in comment


def test_code_review_agent_footer_includes_model():
    """CodeReviewAgent._format_comment includes model line in footer."""
    from app.agents.code_review_agent import CodeReviewAgent

    agent = CodeReviewAgent.__new__(CodeReviewAgent)
    agent.model = "anthropic/claude-3.5-sonnet"

    data = {
        "summary": "Minor refactor with no issues.",
        "files_reviewed": ["app/main.py"],
        "issues_found": [],
        "overall_severity": "low",
    }

    comment = agent._format_comment(data, agent.model)

    assert "*Model: anthropic/claude-3.5-sonnet*" in comment
    assert "*Generated by RepoGator Code Review Agent*" in comment


def test_code_review_agent_footer_uses_custom_model():
    """Code review footer reflects the actual model passed in."""
    from app.agents.code_review_agent import CodeReviewAgent

    agent = CodeReviewAgent.__new__(CodeReviewAgent)
    agent.model = "mistralai/mixtral-8x7b"

    data = {
        "summary": "Summary",
        "files_reviewed": [],
        "issues_found": [],
        "overall_severity": "low",
    }

    comment = agent._format_comment(data, agent.model)
    assert "*Model: mistralai/mixtral-8x7b*" in comment


def test_docs_agent_footer_includes_model_issue():
    """DocsAgent._format_comment includes model line for issue context."""
    from app.agents.docs_agent import DocsAgent

    agent = DocsAgent.__new__(DocsAgent)
    agent.model = "anthropic/claude-3.5-sonnet"

    data = {
        "summary": "This issue tracks a login bug.",
        "technical_notes": "- Check session expiry\n- Validate token",
    }

    comment = agent._format_comment(data, "issue", agent.model)

    assert "*Model: anthropic/claude-3.5-sonnet*" in comment
    assert "*Generated by RepoGator Docs Agent using RAG knowledge base*" in comment
    assert "### Issue Summary" in comment


def test_docs_agent_footer_includes_model_pr():
    """DocsAgent._format_comment includes model line for pull_request context."""
    from app.agents.docs_agent import DocsAgent

    agent = DocsAgent.__new__(DocsAgent)
    agent.model = "google/gemini-pro"

    data = {
        "summary": "This PR fixes the login flow.",
        "technical_notes": "- Updated OAuth handler",
    }

    comment = agent._format_comment(data, "pull_request", agent.model)

    assert "*Model: google/gemini-pro*" in comment
    assert "### Pull Request Summary" in comment


def test_all_agent_footers_consistent_model_format():
    """All three agents use the same '*Model: ...*' footer format."""
    from app.agents.requirements_agent import RequirementsAgent
    from app.agents.code_review_agent import CodeReviewAgent
    from app.agents.docs_agent import DocsAgent

    model = "anthropic/claude-3.5-sonnet"
    expected_line = f"*Model: {model}*"

    req_agent = RequirementsAgent.__new__(RequirementsAgent)
    req_agent.model = model
    req_comment = req_agent._format_comment(
        {"enriched_title": "T", "acceptance_criteria": ["AC"], "edge_cases": ["E"], "suggested_labels": ["l"], "complexity": "S"},
        model,
    )

    cr_agent = CodeReviewAgent.__new__(CodeReviewAgent)
    cr_agent.model = model
    cr_comment = cr_agent._format_comment(
        {"summary": "S", "files_reviewed": [], "issues_found": [], "overall_severity": "low"},
        model,
    )

    docs_agent = DocsAgent.__new__(DocsAgent)
    docs_agent.model = model
    docs_comment = docs_agent._format_comment(
        {"summary": "S", "technical_notes": "N"},
        "issue",
        model,
    )

    assert expected_line in req_comment
    assert expected_line in cr_comment
    assert expected_line in docs_comment
