"""Code review agent using Claude via OpenRouter."""
from openai import AsyncOpenAI
from pydantic import BaseModel
from typing import Literal, Optional
import json
import logging

from app.config import settings
from app.github.client import GitHubClient

logger = logging.getLogger(__name__)


class ReviewIssue(BaseModel):
    file: str
    line: Optional[int]
    severity: Literal["info", "warning", "error", "critical"]
    description: str
    suggestion: str


class CodeReviewOutput(BaseModel):
    summary: str
    files_reviewed: list[str]
    issues_found: list[ReviewIssue]
    overall_severity: Literal["low", "medium", "high", "critical"]
    formatted_comment: str
    tokens_used: int = 0


class CodeReviewAgent:
    """Reviews GitHub PR diffs and provides structured code review."""

    def __init__(
        self,
        github_client: GitHubClient,
        openrouter_api_key: str | None = None,
        openrouter_model: str | None = None,
    ):
        self.github = github_client
        self.model = openrouter_model or settings.openrouter_model
        self.llm = AsyncOpenAI(
            base_url=settings.openrouter_base_url,
            api_key=openrouter_api_key or settings.openrouter_api_key,
        )

    async def process(self, repo: str, pr_number: int, pr_title: str, pr_body: str, correlation_id: str) -> CodeReviewOutput:
        """Review a GitHub pull request and return structured analysis."""
        diff = await self.github.get_pr_diff(repo, pr_number)

        prompt = self._build_prompt(pr_title, pr_body, diff)

        response = await self.llm.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": "You are a senior software engineer doing a thorough code review. Return ONLY valid JSON."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.2,
            response_format={"type": "json_object"},
        )

        tokens_used = response.usage.total_tokens if response.usage else 0
        logger.info(f"Code review agent tokens used: {tokens_used}", extra={"correlation_id": correlation_id})

        raw = json.loads(response.choices[0].message.content)
        raw["formatted_comment"] = self._format_comment(raw)
        raw["tokens_used"] = tokens_used

        return CodeReviewOutput(**raw)

    def _build_prompt(self, title: str, body: str, diff: str) -> str:
        return f"""Review this pull request and provide structured feedback.

PR TITLE: {title}
PR DESCRIPTION: {body or 'No description'}

DIFF:
```diff
{diff}
```

Return a JSON object with:
- summary: 2-3 sentence overview of the PR changes
- files_reviewed: Array of filenames changed
- issues_found: Array of {{file, line (or null), severity ("info"/"warning"/"error"/"critical"), description, suggestion}}
- overall_severity: "low" if no significant issues, "medium" if warnings, "high" if errors, "critical" if security issues

Focus on: security vulnerabilities, logic errors, async/await correctness, missing error handling, performance issues."""

    def _format_comment(self, data: dict) -> str:
        severity_emoji = {"low": "✅", "medium": "⚠️", "high": "🔴", "critical": "🚨"}
        emoji = severity_emoji.get(data["overall_severity"], "ℹ️")

        issues_md = ""
        if data["issues_found"]:
            for issue in data["issues_found"]:
                sev_icons = {"info": "ℹ️", "warning": "⚠️", "error": "🔴", "critical": "🚨"}
                icon = sev_icons.get(issue["severity"], "ℹ️")
                line_ref = f" (line {issue['line']})" if issue.get("line") else ""
                issues_md += f"\n**{icon} {issue['file']}{line_ref}**\n- {issue['description']}\n- 💡 {issue['suggestion']}\n"
        else:
            issues_md = "\n✅ No issues found!"

        files = "\n".join([f"- `{f}`" for f in data["files_reviewed"]])

        return f"""## 🤖 RepoGator — Code Review

**Overall Severity:** {emoji} `{data["overall_severity"].upper()}`

### Summary
{data["summary"]}

### Files Reviewed
{files}

### Issues Found
{issues_md}

---
*Generated by RepoGator Code Review Agent*"""
